version: "3.5"
services:
  orion:
    image: fiware/orion
    hostname: orion
    container_name: fiware-orion-DEA
    depends_on:
      - mongo-db
    ports:
      - "1026:1026"
    command: -dbhost mongo-db -logLevel DEBUG -noCache -corsOrigin __ALL

  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: db-mongo-DEA
    ports:
      - "27017:27017"
    command: --bind_ip_all --smallfiles
    volumes:
      - ./data/mongo-db:/data
      - ./data/mongo-volume:/data/db

  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - ${ADMIN_MONGO_PORT:-1234}:1234
    environment:
      - HOST=0.0.0.0

  cygnus:
    image: fiware/cygnus-ngsi
    hostname: cygnus
    container_name: fiware-cygnus
    networks:
      - default
    ports:
      - 5055:5055
      - 5080:5080
    environment:
      - CYGNUS_MYSQL_SERVICE_PORT=5055
      - CYGNUS_MYSQL_HOST=mysql
      - CYGNUS_MYSQL_PORT=3306
      - CYGNUS_MYSQL_USER=root
      - CYGNUS_MYSQL_PASS= admin123
      - CYGNUS_MYSQL_BATCH_SIZE=1
      - CYGNUS_LOG_LEVEL=INFO
      - CYGNUS_SERVICE_PORT=5055
      - CYGNUS_API_PORT=5080
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.8.3
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=Amlode
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 5004:3306

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24
volumes:
  mysql: ~
